In [2]:
%matplotlib inline
import torch
from d2l import torch as d2l

# 更改打印规则，小数保留位数=2
torch.set_printoptions(precision=2)

假设输入图像的高度为h, 宽度为w
我们以图像的每个像素为中心生成不同形状的锚框：缩放比为s, 属于[0,1]，宽高比 r 
框的宽度 ws sqrt(r) 高 hs/ sqrt(r)

让我们设置许多缩放比（scale）取值  s1 s2 ... sn
和许多宽高比（aspect ratio）取值 r1, r2 ... rm

最终，以同一像素为中心的锚框的数量为 n + m - 1

In [ ]:
# 这里data是图片
# sizes 和 ratios 应该是list
def multibox_prior(data, sizes, ratios):
    """生成以每个像素为中心具有不同形状的锚框"""
    # data.shape -> (B, C, H, W)
    in_height, in_width = data.shape[-2:]
    device, num_sizes, num_ratios = data.device, len(sizes), len(ratios)
    boxes_per_pixel = num_sizes + num_ratios - 1
    size_tensor = torch.tensor(sizes, device = device)
    ratio_tensor = torch.tensor(ratios, device = device)

    # 为了将锚点移动到像素的中心，需要设置偏移量
    # 因为一个像素的高为1 宽为1， 我们选择偏移中心0.5
    offset_h, offset_w = 0.5, 0.5
    # 在y轴上缩放步长
    steps_h = 1.0 / in_height
    steps_w = 1.0 / in_width  # 在x轴上缩放步长

    # 生成锚框的所有中心点
    # 在 [0,1] 区间里，把高度均匀分成 H 份； 每份取中心点
    center_h = (torch.arange(in_height, device=device) + offset_h) * steps_h
    center_w = (torch.arange(in_width, device=device) + offset_w) * steps_w
    shift_y, shift_x = torch.meshgrid(center_h, center_w, indexing='ij')
    shift_y, shift_x = shift_y.reshape(-1), shift_x.reshape(-1)

    # 生成”boxes_per_pixel“个高和宽
    # 之后用于创建锚框的四角坐标(xmin, xmax, ymin, ymax)
    




In [4]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
x = torch.tensor([0, 1, 2])
y = torch.tensor([0, 1, 2, 3])

# X[i, j] = x[i]
# Y[i, j] = y[j]
X, Y = torch.meshgrid(x, y, indexing='ij')

X.reshape(-1), Y.reshape(-1)

(tensor([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]),
 tensor([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))